FROM php:8-fpm-bookworm

LABEL org.opencontainers.image.source="https://github.com/Neomediatech/php" \
      org.label-schema.version=$PHP_VERSION

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Rome \
    VERSION=$PHP_VERSION \
    CUSTOM_PHP_INI_FILE=/usr/local/etc/php-fpm.d/zz-docker.conf

RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y pdfgrep libfcgi-bin netcat-traditional tzdata \
                       whois netbase gettext-base wget && \
    rm -rf /var/lib/apt/lists*

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions

# Install extensions with install-php-extensions, thanks to Michele Locati https://github.com/mlocati
RUN install-php-extensions \
    apcu \
    bcmath \
    bz2 \
    exif \
    gd \
    imap \
    intl \
    mailparse \
    mysqli \
    opcache \
    pdo_mysql \
    redis \
    soap \
    sockets \
    xsl \
    zip \
    gmp \
    sysvsem
 
# Imagick
RUN install-php-extensions imagick

RUN echo "[PHP]" > $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "date.timezone = $TZ" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "expose_php = Off" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "upload_tmp_dir = /tmp" >> $PHP_INI_DIR/conf.d/0-custom.ini

RUN echo "ping.path = /ping" >> $CUSTOM_PHP_INI_FILE && \
    echo "php_admin_value[memory_limit] = 1024M" >> $CUSTOM_PHP_INI_FILE && \
    echo "php_admin_value[post_max_size] = 200M" >> $CUSTOM_PHP_INI_FILE && \
    echo "php_admin_value[upload_max_filesize] = 200M" >> $CUSTOM_PHP_INI_FILE && \
    echo "php_admin_value[max_execution_time] = 300" >> $CUSTOM_PHP_INI_FILE

HEALTHCHECK --interval=10s --timeout=3s --start-period=60s --retries=10 CMD SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1

