FROM php:5.6-apache

LABEL org.label-schema.version=$PHP_VERSION

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Rome

# Update stretch repositories
RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/stretch-updates/d' /etc/apt/sources.list

RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get -y --allow-unauthenticated dist-upgrade && \
    apt-get install -y --allow-unauthenticated libbz2-dev libpng-dev pdfgrep libfcgi-bin libzip-dev netcat tzdata libjpeg-dev libwebp-dev libpq-dev \
                       whois netbase && \
    rm -rf /var/lib/apt/lists*

RUN for mod in mysqli bz2 zip pdo_mysql pdo_pgsql pgsql; do docker-php-ext-install -j$(nproc) $mod ; done && \
    echo "[PHP]" > $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "memory_limit = 1024M" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "post_max_size = 200M" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "upload_max_filesize = 200M" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "max_execution_time = 300" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "date.timezone = $TZ" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "expose_php = Off" >> $PHP_INI_DIR/conf.d/0-custom.ini && \
    echo "upload_tmp_dir = /tmp" >> $PHP_INI_DIR/conf.d/0-custom.ini

# Redis
#RUN pecl bundle -d /usr/src/php/ext redis && \
#    rm -f /usr/src/php/ext/redis-*.tgz && \
#    docker-php-ext-install -j$(nproc) redis

# mailparse
#RUN pecl bundle -d /usr/src/php/ext mailparse && \
#    rm -f /usr/src/php/ext/mailparse-*.tgz && \
#    docker-php-ext-install -j$(nproc) mailparse

# Enable gd support
RUN docker-php-ext-configure gd --with-jpeg --with-webp
RUN docker-php-ext-install -j$(nproc) gd

# Enable EXIF support
RUN docker-php-ext-install -j$(nproc) exif

RUN echo "ServerTokens Prod" > $APACHE_CONFDIR/conf-enabled/zz-custom.conf && \
    echo "ServerSignature Off" >> $APACHE_CONFDIR/conf-enabled/zz-custom.conf && \
    echo '<Location "/server-status">' >> $APACHE_CONFDIR/conf-enabled/zz-custom.conf && \
    echo "  SetHandler server-status" >> $APACHE_CONFDIR/conf-enabled/zz-custom.conf && \
    echo "  Require  host  localhost" >> $APACHE_CONFDIR/conf-enabled/zz-custom.conf && \
    echo "</Location>" >> $APACHE_CONFDIR/conf-enabled/zz-custom.conf 

# Rewrite engine
RUN a2enmod rewrite

HEALTHCHECK --interval=60s --timeout=5s --start-period=60s --retries=10 CMD curl -sS localhost/server-status?auto | grep -E "ServerVersion|RestartTime|ServerUptime:" && echo "Gimme a page" || exit 1
