FROM php:8.4-apache-bookworm

LABEL org.label-schema.version=$PHP_VERSION

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Rome

RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y pdfgrep libfcgi-bin netcat-traditional tzdata \
                       whois netbase gettext-base wget && \
    rm -rf /var/lib/apt/lists*

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions

ENV MODULES="apcu bcmath bz2 exif gd imap intl mailparse mysqli opcache pdo_mysql"
ENV MODULES="$MODULES redis soap sockets xsl zip gmp sysvsem imagick"
# Install extensions with install-php-extensions, thanks to Michele Locati https://github.com/mlocati
RUN install-php-extensions $MODULES

# Enable rewrite,  ssl, info, remoteip modules
RUN a2enmod rewrite ssl info remoteip

# Create custom snippets directory
RUN mkdir -p $APACHE_CONFDIR/conf-custom && \
    echo "# Include custom snippets directory:" >> $APACHE_CONFDIR/apache2.conf && \
    echo "IncludeOptional conf-custom/*.conf" >> $APACHE_CONFDIR/apache2.conf

COPY 0-custom.ini $PHP_INI_DIR/conf.d/
COPY zz-custom.conf $APACHE_CONFDIR/conf-enabled/

# setup some ENV vars to allow customi[s|z]ations
ENV APACHE_START_SERVERS="5" \
    APACHE_MIN_SPARE_SERVERS="5" \
    APACHE_MAX_SPARE_SERVERS="10" \
    APACHE_MAX_REQUEST_WORKERS="150" \
    APACHE_MAX_CONNECTIONS_PER_CHILD="0" \
    APACHE_SERVER_LIMIT="256"

COPY --chmod=444 mpm_prefork.conf.template $APACHE_CONFDIR/

COPY --chmod=755 custom-entrypoint /

ENTRYPOINT ["/custom-entrypoint"]
CMD ["apache2-foreground"]

HEALTHCHECK --interval=60s --timeout=5s --start-period=60s --retries=10 CMD curl -sS localhost/server-status?auto | grep -E "ServerVersion|RestartTime|ServerUptime:" && echo "Gimme a page" || exit 1

