name: Build and Scan Docker Image

on:
  #push:
  #  branches: [master]
  #pull_request:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub

jobs:
  build-and-scan:
    secrets: inherit
    strategy:
      matrix:
        target: [8, 8.1, 8.2, 8.3, 8.4]
    uses: Neomediatech/gh-workflow/.github/workflows/build-and-scan-docker-image.yml@main
    with:
      dockerfile: "Dockerfile.${{ matrix.target }}"
      dockerdir: "8-apache"
      dockertag: ${{ matrix.target }}-apache

  push-report-to-repo:
    strategy:
      matrix:
        target: [8, 8.1, 8.2, 8.3, 8.4]
      max-parallel: 1
    needs: [build-and-scan]
    secrets: inherit
    uses: Neomediatech/gh-workflow/.github/workflows/copy-file-to-another-repo.yml@main
    with:
      file_id: ${{ needs.build-and-scan.outputs.uploaded-file-id }}
      filename: ${{ needs.build-and-scan.outputs.file_to_copy_output }}
      dockertag: ${{ matrix.target }}-apache

