# questo workflow viene chiamato via curl con questa chiamata:
# curl -X POST \
#  -H "Accept: application/vnd.github+json" \
#  -H "Authorization: Bearer __github_api_key__" \
#  https://api.github.com/repos/Neomediatech/php/dispatches \
#  -d '{
#    "event_type": "build-php",
#    "client_payload": {
#      "var_1": "valore di esempio",
#      "var_2": "altro valore"
#    }
#  }'

name: Build PHP Docker Images via curl

on:
  repository_dispatch: # Per inviare richieste di compilazione immagini via curl
    types: [build-php] # ascolta eventi con questo nome
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-image:
    uses: Neomediatech/gh-workflows/.github/workflows/build-docker-image.yml@main
    secrets: inherit
    with:
      base-image: php
